name: Build and Deploy Next.js App with Artifacts

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install dependencies and build the app
      - name: Install Dependencies and Build
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        run: |
          npm ci --omit=dev
          npm run build

      # Prune unnecessary dependencies
      - name: Prune Node Modules
        run: npm prune --production

      # Save deployment package as artifact
      - name: Upload Deployment Artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployment-package
          path: |
            .next
            node_modules
            package.json
            public

      # Deploy the artifact to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hiipitch-scheduling-app-dev-azs'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4385ACEF9DF8458AA19B97ACE948ED13 }}
          package: deployment-package